import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";

import { getServerAuthSession } from "../../server/auth";
import BaseLayout from "../../components/layout/Layout";
import RegisterForm from "../../components/form/RegisterForm";

const Register: NextPage = () => {
  return (
    <>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <BaseLayout> */}
      <RegisterForm />
      {/* </BaseLayout> */}
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getServerAuthSession({
    req: context.req,
    res: context.res,
  });
  // If user is authed no login :3
  if (session) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }

  return { props: {} };
};

export default Register;
