import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import ShopLatest from "../components/ShopLatest";
import Carousel from "../components/Carousel";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  // const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>My First T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Carousel />
        <ShopLatest />
      </main>
    </>
  );
};

export default Home;
